import { NextRequest, NextResponse } from 'next/server'
import bcrypt from 'bcryptjs'
import { createServiceClient } from '@/lib/supabase-server'
import { handleError, errorResponse } from '@/lib/api-helpers'
import * as crmRepo from '@/repositories/crm.repository'
import * as portalRepo from '@/repositories/portal.repository'
import { z } from 'zod'

const signupSchema = z.object({
  workspace_slug: z.string().min(3).max(30).regex(/^[a-z0-9-]+$/, 'Invalid workspace slug format.'),
  name:           z.string().min(1).max(200).trim(),
  email:          z.string().email().toLowerCase(),
  password:       z.string().min(8).max(128),
  contact_id:     z.string().uuid(),
})

/**
 * POST /api/v1/portal/auth/signup
 *
 * Creates a portal client account scoped to a specific workspace.
 * Does NOT create a Supabase Auth user — uses bcrypt + custom JWT instead.
 * The same email can exist in different workspaces without conflict.
 *
 * Body: { workspace_slug, name, email, password, contact_id }
 */
export async function POST(req: NextRequest) {
  let body: unknown
  try { body = await req.json() } catch {
    return errorResponse('PORTAL_SIGNUP_INVALID_BODY', 'Invalid request body.', 400)
  }

  const parsed = signupSchema.safeParse(body)
  if (!parsed.success) {
    return errorResponse(
      'PORTAL_SIGNUP_VALIDATION',
      parsed.error.issues[0]?.message ?? 'Invalid signup details.',
      400,
    )
  }

  const { workspace_slug, name, email, password, contact_id } = parsed.data

  try {
    const db = createServiceClient()

    // 1. Resolve workspace owner
    const ownerRow = await portalRepo.getOwnerIdByWorkspaceSlug(db, workspace_slug)
    if (!ownerRow) {
      return errorResponse('PORTAL_NOT_FOUND', 'Workspace not found.', 404)
    }

    // 2. Check portal is active
    const branding = await portalRepo.getOwnerByWorkspaceSlug(db, workspace_slug)
    if (!branding?.portal_active) {
      return errorResponse('PORTAL_INACTIVE', 'This portal is not currently active.', 403)
    }

    const { user_id: ownerId, business_email: ownerEmail } = ownerRow

    // 3. Verify contact exists and belongs to this owner
    const contact = await portalRepo.getContactById(db, contact_id)
    if (!contact) {
      return errorResponse('CRM_CONTACT_NOT_FOUND', 'Contact not found.', 404)
    }
    if (contact.owner_id !== ownerId) {
      return errorResponse('PORTAL_ACCESS_DENIED', 'Access denied.', 403)
    }
    if (!contact.portal_enabled) {
      return errorResponse('PORTAL_DISABLED', 'Portal access is not enabled for this contact.', 403)
    }

    // 4. Reject duplicate email within this workspace
    const emailTaken = await portalRepo.portalEmailExistsInWorkspace(db, workspace_slug, email)
    if (emailTaken) {
      return errorResponse(
        'PORTAL_SIGNUP_EMAIL_TAKEN',
        'An account with this email already exists in this workspace.',
        409,
      )
    }

    // 5. Hash password (12 rounds — secure without being unreasonably slow)
    const password_hash = await bcrypt.hash(password, 12)

    // 6. Create portal_users row (id generated by DB default gen_random_uuid())
    const portalUser = await portalRepo.createPortalUser(db, {
      contact_id,
      owner_id:       ownerId,
      workspace_slug,
      name,
      email,
      password_hash,
      avatar_url: null,
    })

    // 7. Notify owner in-app
    await crmRepo.createNotification(
      db,
      ownerId,
      contact_id,
      'client_signup',
      `${name} joined your portal`,
    )

    // 8. Email owner (non-fatal)
    try {
      const resendKey = process.env.RESEND_API_KEY
      if (resendKey && ownerEmail) {
        const { Resend } = await import('resend')
        const resend = new Resend(resendKey)
        const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? ''
        await resend.emails.send({
          from:    'Fey Workboard <notifications@feyapp.com>',
          to:      [ownerEmail],
          subject: `${name} joined your portal`,
          html: `<p><strong>${name}</strong> (${email}) just signed up to your client portal.</p>
                 ${appUrl ? `<p><a href="${appUrl}/clients/${contact_id}/messages">View their workspace</a></p>` : ''}`,
        })
      }
    } catch {
      // Email failure is non-fatal
    }

    return NextResponse.json({ success: true, userId: portalUser.id }, { status: 201 })
  } catch (err) {
    return handleError(err, 'PORTAL_SIGNUP_FAILED')
  }
}
