import { NextRequest, NextResponse } from 'next/server'
import bcrypt from 'bcryptjs'
import { escapeHtml } from '@/utils/escapeHtml'
import { createServiceClient } from '@/lib/supabase-server'
import { signPortalToken } from '@/lib/portal-jwt'
import { handleError, errorResponse } from '@/lib/api-helpers'
import { notifyOwnerAdmins } from '@/services/notifications.service'
import * as portalRepo from '@/repositories/portal.repository'
import { sendEmail } from '@/services/email.service'
import { appUrl } from '@/config/email'
import { z } from 'zod'

const signupSchema = z.object({
  workspace_slug: z.string().min(3).max(30).regex(/^[a-z0-9-]+$/, 'Invalid workspace slug format.'),
  name:           z.string().min(1).max(200).trim(),
  email:          z.string().email().toLowerCase(),
  password:       z.string().min(8).max(128),
  // invite_code is the short 8-char code on crm_contacts (e.g. "A3B7X9M2").
  // The old field was contact_id (UUID) — we keep backward compat by accepting either.
  invite_code:    z.string().min(4).max(32).optional(),
  contact_id:     z.string().uuid().optional(),
}).refine((d) => d.invite_code ?? d.contact_id, {
  message: 'Either invite_code or contact_id is required.',
})

/**
 * POST /api/v1/portal/auth/signup
 *
 * Creates a portal client account scoped to a specific workspace.
 * Does NOT create a Supabase Auth user — uses bcrypt + custom JWT instead.
 * The same email can exist in different workspaces without conflict.
 *
 * Body: { workspace_slug, name, email, password, contact_id }
 */
export async function POST(req: NextRequest) {
  let body: unknown
  try { body = await req.json() } catch {
    return errorResponse('PORTAL_SIGNUP_INVALID_BODY', 'Invalid request body.', 400)
  }

  const parsed = signupSchema.safeParse(body)
  if (!parsed.success) {
    return errorResponse(
      'PORTAL_SIGNUP_VALIDATION',
      parsed.error.issues[0]?.message ?? 'Invalid signup details.',
      400,
    )
  }

  const { workspace_slug, name, email, password, invite_code, contact_id } = parsed.data

  try {
    const db = createServiceClient()

    // 1. Resolve workspace owner
    const ownerRow = await portalRepo.getOwnerIdByWorkspaceSlug(db, workspace_slug)
    if (!ownerRow) {
      return errorResponse('PORTAL_NOT_FOUND', 'Workspace not found.', 404)
    }

    // 2. Check portal is active
    const branding = await portalRepo.getOwnerByWorkspaceSlug(db, workspace_slug)
    if (!branding?.portal_active) {
      return errorResponse('PORTAL_INACTIVE', 'This portal is not currently active.', 403)
    }

    const { user_id: ownerId, business_email: ownerEmail } = ownerRow

    // 3. Resolve contact — prefer invite_code lookup, fall back to contact_id UUID
    let contact
    if (invite_code) {
      contact = await portalRepo.getContactByInviteCode(db, invite_code)
      if (!contact) {
        return errorResponse('PORTAL_INVALID_CODE', 'Invalid invite code. Please check the link you were sent.', 404)
      }
    } else if (contact_id) {
      contact = await portalRepo.getContactById(db, contact_id)
      if (!contact) {
        return errorResponse('CRM_CONTACT_NOT_FOUND', 'Contact not found.', 404)
      }
    }

    if (!contact) {
      return errorResponse('PORTAL_INVALID_CODE', 'Invalid invite code.', 400)
    }
    if (contact.owner_id !== ownerId) {
      return errorResponse('PORTAL_ACCESS_DENIED', 'Access denied.', 403)
    }
    if (!contact.portal_enabled) {
      return errorResponse('PORTAL_DISABLED', 'Portal access is not enabled for this contact.', 403)
    }

    // 4. Reject duplicate email within this workspace
    const emailTaken = await portalRepo.portalEmailExistsInWorkspace(db, workspace_slug, email)
    if (emailTaken) {
      return errorResponse(
        'PORTAL_SIGNUP_EMAIL_TAKEN',
        'An account with this email already exists in this workspace.',
        409,
      )
    }

    // 5. Hash password (12 rounds — secure without being unreasonably slow)
    const password_hash = await bcrypt.hash(password, 12)

    // 6. Create portal_users row (id generated by DB default gen_random_uuid())
    const portalUser = await portalRepo.createPortalUser(db, {
      contact_id: contact.id,
      owner_id:       ownerId,
      workspace_slug,
      name,
      email,
      password_hash,
      avatar_url: null,
    })

    // 7. Notify owner + admins in-app (+ push)
    await notifyOwnerAdmins(db, ownerId, {
      type: 'client_signup',
      title: `${name} joined your portal`,
      link: `/clients/${contact.id}/messages`,
      entityType: 'contact',
      entityId: contact.id,
    })

    // 8. Email owner (non-fatal — sendEmail never throws)
    if (ownerEmail) {
      const base = appUrl()
      // name/email are client-chosen — escape before embedding in the email HTML.
      const safeName = escapeHtml(name)
      const safeEmail = escapeHtml(email)
      await sendEmail({
        from:    'Fey Workboard <notifications@feyapp.com>',
        to:      [ownerEmail],
        subject: `${name} joined your portal`,
        html: `<p><strong>${safeName}</strong> (${safeEmail}) just signed up to your client portal.</p>
               <p><a href="${base}/clients/${contact_id}/messages">View their workspace</a></p>`,
      })
    }

    // Issue a session token so the client is signed in immediately (no re-login).
    const token = await signPortalToken({
      portal_user_id: portalUser.id,
      contact_id:     portalUser.contact_id,
      owner_id:       ownerId,
      workspace_slug,
    })

    return NextResponse.json({
      success: true,
      token,
      user: { id: portalUser.id, name: portalUser.name, email: portalUser.email, contact_id: portalUser.contact_id },
    }, { status: 201 })
  } catch (err) {
    return handleError(err, 'PORTAL_SIGNUP_FAILED')
  }
}
