import type { SupabaseClient } from '@supabase/supabase-js'
import type {
  CrmContact, CrmMessage, CrmFile, CrmContract, CrmForm,
  PortalUser, CreatePortalUserPayload, PortalOwnerBranding,
  MessageAttachment, ContractContent, FormField, FormResponse,
  PortalInvoice, PortalPayment, PortalTask, PaymentRequestStatus,
} from '@/types/crm'

// ── Owner lookup by workspace_slug ────────────────────────────────────────────

export async function getOwnerByWorkspaceSlug(
  db: SupabaseClient,
  workspaceSlug: string,
): Promise<PortalOwnerBranding | null> {
  const { data, error } = await db
    .from('fey_settings')
    .select('user_id, username, company_name, logo, accent_color, font_family, workspace_slug, workspace_name, portal_active')
    .eq('workspace_slug', workspaceSlug)
    .maybeSingle()
  if (error ?? !data) return null
  const row = data as Record<string, unknown>
  return {
    business_name: (row.company_name as string | null) || (row.workspace_name as string | null) || 'Workspace',
    owner_name:    (row.username as string | null) ?? '',
    logo_url:      (row.logo as string | null) ?? null,
    accent_color:  (row.accent_color as string | null) ?? '#ED64A6',
    font:          (row.font_family as string | null) ?? 'NoirPro',
    subdomain:     row.workspace_slug as string,
    portal_active: (row.portal_active as boolean | null) ?? false,
  }
}

// Keep the old name as an alias so code that still uses it doesn't break
export const getOwnerBySubdomain = getOwnerByWorkspaceSlug

// ── Owner identity lookup ─────────────────────────────────────────────────────

export async function getOwnerIdByWorkspaceSlug(
  db: SupabaseClient,
  workspaceSlug: string,
): Promise<{ user_id: string; business_email: string | null } | null> {
  const { data, error } = await db
    .from('fey_settings')
    .select('user_id, business_email')
    .eq('workspace_slug', workspaceSlug)
    .maybeSingle()
  if (error ?? !data) return null
  const row = data as Record<string, unknown>
  return {
    user_id:        row.user_id as string,
    business_email: (row.business_email as string | null) ?? null,
  }
}

// ── Portal user lookup ────────────────────────────────────────────────────────

export async function getPortalUser(
  db: SupabaseClient,
  portalUserId: string,
): Promise<PortalUser | null> {
  const { data, error } = await db
    .from('portal_users')
    .select('id, contact_id, owner_id, workspace_slug, name, email, avatar_url, created_at')
    .eq('id', portalUserId)
    .maybeSingle()
  if (error ?? !data) return null
  return data as PortalUser
}

export async function getPortalUserByWorkspaceAndEmail(
  db: SupabaseClient,
  workspaceSlug: string,
  email: string,
): Promise<(PortalUser & { password_hash: string | null }) | null> {
  const { data, error } = await db
    .from('portal_users')
    .select('id, contact_id, owner_id, workspace_slug, name, email, avatar_url, created_at, password_hash')
    .eq('workspace_slug', workspaceSlug)
    .eq('email', email)
    .maybeSingle()
  if (error ?? !data) return null
  return data as PortalUser & { password_hash: string | null }
}

export async function getPortalUserByContactAndOwner(
  db: SupabaseClient,
  contactId: string,
  ownerId: string,
): Promise<PortalUser | null> {
  const { data, error } = await db
    .from('portal_users')
    .select('id, contact_id, owner_id, workspace_slug, name, email, avatar_url, created_at')
    .eq('contact_id', contactId)
    .eq('owner_id', ownerId)
    .maybeSingle()
  if (error ?? !data) return null
  return data as PortalUser
}

export async function portalEmailExistsInWorkspace(
  db: SupabaseClient,
  workspaceSlug: string,
  email: string,
): Promise<boolean> {
  const { data } = await db
    .from('portal_users')
    .select('id')
    .eq('workspace_slug', workspaceSlug)
    .eq('email', email)
    .maybeSingle()
  return data !== null
}

export async function createPortalUser(
  db: SupabaseClient,
  payload: CreatePortalUserPayload,
): Promise<PortalUser> {
  const { data, error } = await db
    .from('portal_users')
    .insert({
      // id is omitted — generated by gen_random_uuid() in Postgres
      contact_id:     payload.contact_id,
      owner_id:       payload.owner_id,
      workspace_slug: payload.workspace_slug,
      name:           payload.name,
      email:          payload.email,
      password_hash:  payload.password_hash,
      avatar_url:     payload.avatar_url,
    })
    .select('id, contact_id, owner_id, workspace_slug, name, email, avatar_url, created_at')
    .single()
  if (error) throw error
  return data as PortalUser
}

// ── Contact for portal client ─────────────────────────────────────────────────

export async function getContactForPortalUser(
  db: SupabaseClient,
  contactId: string,
  ownerId: string,
): Promise<CrmContact | null> {
  const { data, error } = await db
    .from('crm_contacts')
    .select('*')
    .eq('id', contactId)
    .eq('owner_id', ownerId)
    .eq('portal_enabled', true)
    .maybeSingle()
  if (error ?? !data) return null
  return data as CrmContact
}

export async function getContactById(
  db: SupabaseClient,
  contactId: string,
): Promise<CrmContact | null> {
  const { data, error } = await db
    .from('crm_contacts')
    .select('*')
    .eq('id', contactId)
    .maybeSingle()
  if (error ?? !data) return null
  return data as CrmContact
}

/** Look up a contact by its short invite_code. Used during portal signup. */
export async function getContactByInviteCode(
  db: SupabaseClient,
  inviteCode: string,
): Promise<CrmContact | null> {
  const { data, error } = await db
    .from('crm_contacts')
    .select('*')
    .eq('invite_code', inviteCode.toUpperCase())
    .maybeSingle()
  if (error ?? !data) return null
  return data as CrmContact
}

// ── Portal messages ───────────────────────────────────────────────────────────

export async function listPortalMessages(
  db: SupabaseClient,
  contactId: string,
): Promise<CrmMessage[]> {
  const { data, error } = await db
    .from('crm_messages')
    .select('*')
    .eq('contact_id', contactId)
    .order('created_at', { ascending: true })
  if (error) throw error
  return (data ?? []).map(rowToMessage)
}

export async function createPortalMessage(
  db: SupabaseClient,
  ownerId: string,
  senderId: string,
  contactId: string,
  body: string,
  bodyHtml: string | null,
  attachments: MessageAttachment[],
): Promise<CrmMessage> {
  const { data, error } = await db
    .from('crm_messages')
    .insert({
      contact_id:  contactId,
      owner_id:    ownerId,
      sender_type: 'client',
      sender_id:   senderId,
      body,
      body_html:   bodyHtml,
      attachments,
    })
    .select()
    .single()
  if (error) throw error
  return rowToMessage(data)
}

function rowToMessage(row: Record<string, unknown>): CrmMessage {
  return {
    id:          row.id as string,
    contact_id:  row.contact_id as string,
    owner_id:    row.owner_id as string,
    sender_type: row.sender_type as 'owner' | 'client',
    sender_id:   row.sender_id as string,
    body:        row.body as string,
    body_html:   (row.body_html as string | null) ?? null,
    attachments: (row.attachments as MessageAttachment[]) ?? [],
    read_at:     (row.read_at as string | null) ?? null,
    created_at:  row.created_at as string,
  }
}

// ── Portal files ──────────────────────────────────────────────────────────────

export async function listPortalFiles(
  db: SupabaseClient,
  contactId: string,
): Promise<CrmFile[]> {
  const { data, error } = await db
    .from('crm_files')
    .select('*')
    .eq('contact_id', contactId)
    .order('created_at', { ascending: false })
  if (error) throw error
  return (data ?? []) as CrmFile[]
}

// ── Portal contracts ──────────────────────────────────────────────────────────

export async function listPortalContracts(
  db: SupabaseClient,
  contactId: string,
): Promise<CrmContract[]> {
  const { data, error } = await db
    .from('crm_contracts')
    .select('*')
    .eq('contact_id', contactId)
    .in('status', ['sent', 'signed', 'declined'])
    .order('created_at', { ascending: false })
  if (error) throw error
  return (data ?? []).map((row: Record<string, unknown>) => ({
    id:          row.id as string,
    contact_id:  row.contact_id as string,
    owner_id:    row.owner_id as string,
    title:       row.title as string,
    share_token: row.share_token as string,
    status:      row.status as CrmContract['status'],
    content:     row.content as ContractContent,
    signed_at:   (row.signed_at as string | null) ?? null,
    created_at:  row.created_at as string,
    updated_at:  row.updated_at as string,
  }))
}

export async function signContract(
  db: SupabaseClient,
  contractId: string,
  contactId: string,
): Promise<void> {
  const { error } = await db
    .from('crm_contracts')
    .update({ status: 'signed', signed_at: new Date().toISOString(), updated_at: new Date().toISOString() })
    .eq('id', contractId)
    .eq('contact_id', contactId)
    .eq('status', 'sent')
  if (error) throw error
}

// ── Portal forms ──────────────────────────────────────────────────────────────

export async function listPortalForms(
  db: SupabaseClient,
  contactId: string,
): Promise<CrmForm[]> {
  const { data, error } = await db
    .from('crm_forms')
    .select('*')
    .eq('contact_id', contactId)
    .in('status', ['sent', 'submitted'])
    .order('created_at', { ascending: false })
  if (error) throw error
  return (data ?? []).map((row: Record<string, unknown>) => ({
    id:           row.id as string,
    contact_id:   row.contact_id as string,
    owner_id:     row.owner_id as string,
    title:        row.title as string,
    share_token:  row.share_token as string,
    status:       row.status as CrmForm['status'],
    fields:       (row.fields as FormField[]) ?? [],
    responses:    (row.responses as FormResponse[]) ?? [],
    submitted_at: (row.submitted_at as string | null) ?? null,
    created_at:   row.created_at as string,
    updated_at:   row.updated_at as string,
  }))
}

export async function submitForm(
  db: SupabaseClient,
  formId: string,
  contactId: string,
  responses: FormResponse[],
): Promise<void> {
  const { error } = await db
    .from('crm_forms')
    .update({
      status:       'submitted',
      responses,
      submitted_at: new Date().toISOString(),
      updated_at:   new Date().toISOString(),
    })
    .eq('id', formId)
    .eq('contact_id', contactId)
    .eq('status', 'sent')
  if (error) throw error
}

// ── Portal invoices ───────────────────────────────────────────────────────────
// Invoices link to a CRM contact via crm_contact_id. Only surface invoices the
// owner has actually sent — never drafts or voided ones.

export async function listPortalInvoices(
  db: SupabaseClient,
  contactId: string,
): Promise<PortalInvoice[]> {
  const { data, error } = await db
    .from('invoices')
    .select('id, invoice_number, status, totals, currency, due_date, share_token, share_enabled, created_at')
    .eq('crm_contact_id', contactId)
    .in('status', ['sent', 'viewed', 'paid', 'overdue'])
    .order('created_at', { ascending: false })
  if (error) throw error
  return (data ?? []).map((row: Record<string, unknown>) => ({
    id:             row.id as string,
    invoice_number: (row.invoice_number as string | null) ?? '',
    status:         row.status as string,
    amount:         (row.totals as { total?: number } | null)?.total ?? 0,
    currency:       (row.currency as string | null) ?? 'USD',
    due_date:       (row.due_date as string | null) ?? null,
    share_token:    (row.share_token as string | null) ?? null,
    share_enabled:  (row.share_enabled as boolean | null) ?? false,
    created_at:     row.created_at as string,
  }))
}

// ── Portal payment requests ─────────────────────────────────────────────────
// crm_payment_requests are payment links the owner sends to a contact. Show
// everything except cancelled ones (those were withdrawn).

export async function listPortalPayments(
  db: SupabaseClient,
  contactId: string,
): Promise<PortalPayment[]> {
  const { data, error } = await db
    .from('crm_payment_requests')
    .select('id, description, amount, currency, status, share_token, created_at')
    .eq('contact_id', contactId)
    .in('status', ['pending', 'paid', 'expired'])
    .order('created_at', { ascending: false })
  if (error) throw error
  return (data ?? []).map((row: Record<string, unknown>) => ({
    id:          row.id as string,
    description: (row.description as string | null) ?? '',
    amount:      (row.amount as number | null) ?? 0,
    currency:    (row.currency as string | null) ?? 'USD',
    status:      row.status as PaymentRequestStatus,
    share_token: (row.share_token as string | null) ?? null,
    created_at:  row.created_at as string,
  }))
}

// ── Portal tasks ──────────────────────────────────────────────────────────────
// Tasks link to a CRM contact via client_id. Surface only title + done status —
// pricing (amount/paid) stays internal to the owner.

export async function listPortalTasks(
  db: SupabaseClient,
  contactId: string,
): Promise<PortalTask[]> {
  const { data, error } = await db
    .from('tasks')
    .select('id, title, done, created_at')
    .eq('client_id', contactId)
    .order('created_at', { ascending: true })
  if (error) throw error
  return (data ?? []).map((row: Record<string, unknown>) => ({
    id:         row.id as string,
    title:      row.title as string,
    done:       (row.done as boolean | null) ?? false,
    created_at: row.created_at as string,
  }))
}

// ── Owner settings lookup ─────────────────────────────────────────────────────

export async function getOwnerSettings(
  db: SupabaseClient,
  ownerId: string,
): Promise<Record<string, unknown> | null> {
  const { data, error } = await db
    .from('fey_settings')
    .select('*')
    .eq('user_id', ownerId)
    .maybeSingle()
  if (error ?? !data) return null
  return data as Record<string, unknown>
}
