-- Client sharing system: owners share a client workspace with external members
-- using invite codes. Three tables form the system:
--
--   shared_clients          — one row per shared workspace (owner → client link)
--   shared_client_invites   — invite codes generated by the owner
--   shared_client_members   — people who have joined via an invite code
--
-- The share token is a UUID used in the public share URL (/share/<token>).
-- It is auto-generated on insert via a trigger (see bottom of file).

-- ── shared_clients ────────────────────────────────────────────────────────────

create table if not exists public.shared_clients (
  id           uuid        primary key default gen_random_uuid(),
  client_id    uuid        not null references public.clients(id) on delete cascade,
  owner_id     uuid        not null references auth.users(id) on delete cascade,
  owner_name   text        not null default '',
  permission   text        not null default 'view',   -- view | edit
  active       boolean     not null default true,
  -- Cached copies of client fields so the share page works without owner's RLS
  client_name  text        not null default '',
  client_color text        not null default '#D1FAE5',
  client_logo  text        not null default '',
  -- Public URL token — generated by trigger below, never null
  token        text        unique not null default gen_random_uuid()::text,
  created_at   timestamptz not null default now()
);

alter table public.shared_clients enable row level security;

-- Owners manage their own share records
create policy "shared_clients_select_owner"
  on public.shared_clients for select
  using (auth.uid() = owner_id);

create policy "shared_clients_insert_owner"
  on public.shared_clients for insert
  with check (auth.uid() = owner_id);

create policy "shared_clients_update_owner"
  on public.shared_clients for update
  using (auth.uid() = owner_id);

create policy "shared_clients_delete_owner"
  on public.shared_clients for delete
  using (auth.uid() = owner_id);

-- Public access via share token (drives the /share/<token> page)
create policy "shared_clients_select_public"
  on public.shared_clients for select
  using (active = true);

create index if not exists idx_shared_clients_owner
  on public.shared_clients(owner_id);

create index if not exists idx_shared_clients_token
  on public.shared_clients(token)
  where active = true;

-- ── shared_client_invites ─────────────────────────────────────────────────────

create table if not exists public.shared_client_invites (
  id               uuid        primary key default gen_random_uuid(),
  shared_client_id uuid        not null references public.shared_clients(id) on delete cascade,
  code             text        not null unique,
  label            text,
  status           text        not null default 'pending',  -- pending | used | revoked
  member_id        uuid,       -- FK added after shared_client_members is created
  member_name      text,
  created_at       timestamptz not null default now()
);

alter table public.shared_client_invites enable row level security;

-- Owners read and manage codes for their shared clients
create policy "shared_client_invites_owner"
  on public.shared_client_invites for all
  using (
    exists (
      select 1 from public.shared_clients sc
      where sc.id = shared_client_id
        and sc.owner_id = auth.uid()
    )
  );

-- Anyone can read a pending code (needed by /share/<token> page to validate)
create policy "shared_client_invites_select_public"
  on public.shared_client_invites for select
  using (true);

create index if not exists idx_shared_client_invites_shared
  on public.shared_client_invites(shared_client_id);

create index if not exists idx_shared_client_invites_code
  on public.shared_client_invites(code);

-- ── shared_client_members ─────────────────────────────────────────────────────

create table if not exists public.shared_client_members (
  id               uuid        primary key default gen_random_uuid(),
  shared_client_id uuid        not null references public.shared_clients(id) on delete cascade,
  name             text        not null,
  permission       text                    default 'view',  -- view | edit | null → inherits from shared_clients
  joined_at        timestamptz not null default now()
);

alter table public.shared_client_members enable row level security;

-- Owners manage members of their shared workspaces
create policy "shared_client_members_owner"
  on public.shared_client_members for all
  using (
    exists (
      select 1 from public.shared_clients sc
      where sc.id = shared_client_id
        and sc.owner_id = auth.uid()
    )
  );

-- Anyone can read and insert member rows (needed by /share/<token> join flow)
create policy "shared_client_members_select_public"
  on public.shared_client_members for select
  using (true);

create policy "shared_client_members_insert_public"
  on public.shared_client_members for insert
  with check (true);

create index if not exists idx_shared_client_members_shared
  on public.shared_client_members(shared_client_id);

-- ── whats_new ─────────────────────────────────────────────────────────────────
-- Content-managed table of product changelog entries shown in the app.
-- Written manually (or via Supabase Studio) by the product team; no user auth needed to read.

create table if not exists public.whats_new (
  id         uuid        primary key default gen_random_uuid(),
  version    text        not null unique,
  title      text        not null,
  features   jsonb       not null default '[]',
  created_at timestamptz not null default now()
);

alter table public.whats_new enable row level security;

-- Public read — anyone (including unauthenticated) can read changelog entries
create policy "whats_new_select_public"
  on public.whats_new for select
  using (true);
